//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class forDataBase2Entities : DbContext
    {
        public forDataBase2Entities()
            : base("name=forDataBase2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<table1> table1 { get; set; }

        private static forDataBase2Entities context;
        public static forDataBase2Entities GetContext()
        {
            if (context == null)
            {
                context = new forDataBase2Entities();
            }
            return context;
        }
    }
}
