//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data2
{
    using System;
    using System.Collections.Generic;
    
    public partial class table1
    {
        public int Код_обуви { get; set; }
        public string Артикул_обуви { get; set; }
        public string Наименование_обуви { get; set; }
        public Nullable<int> Количество_пар { get; set; }
        public Nullable<int> Стоимость_одной_пары { get; set; }
        public Nullable<int> Имеющиеся_размеры { get; set; }
        public string Название_фабрики { get; set; }
        public Nullable<System.DateTime> Срок_поставки_в_магазин { get; set; }
    }
}
