//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Авторизация
    {
        public int Код { get; set; }
        public string Логин { get; set; }
        public Nullable<int> Пароль { get; set; }
        public string Доступ { get; set; }
        public string Почта { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
    }
}
